  db_name = "pg_core_us_100_stg"
  db_instance_name = "pg-core-us-100-stg"
  db_type = "postgres"
  db_version = "POSTGRES_15"
  db_tier = "db-custom-4-16384"
  db_tier_replica = "db-custom-2-12288" 
  disk_size = 1000
  log_connections = "on"
  pg_cron = "on"
  replica_count = 1
#  max_worker_processes = 32
#  max_logical_replication_workers = 24
#  max_wal_senders = 25
#  max_replication_slots = 20
