  db_name = "pg_stable_test"
  db_instance_name = "pg-stable-test"
  db_type = "postgres"
  db_version = "POSTGRES_15"
  db_tier = "db-custom-4-15360"
  log_connections = "on"
  max_wal_senders = 10
  pg_cron = "on"
#  db_user_name = "my_test_app"
#  db_user_password = "gds123test"
  replica_count = 1
  max_wal_senders = 25
  max_replication_slots = 20
