  db_name = "pg_noncore_us_007_stg"
  db_instance_name = "pg-noncore-us-007-stg"
  db_type = "postgres"
  db_version = "POSTGRES_14"
  db_tier = "db-custom-4-15360"
  disk_size = 1000
  log_connections = "on"
  pg_cron = "on"
#  db_user_name = "my_test_app"
#  db_user_password = "gds123test"
  replica_count = 1
  max_worker_processes = 16
  max_logical_replication_workers = 12
  max_wal_senders = 10
  max_replication_slots = 10
