#!/usr/bin/env bash

# Save current instance pointer
current_instance=$(current_instance)

[ $# -gt 0 ] && instances=$@ || instances=$(list_instances | awk '{print $NF}')

# Perform action
for instance in ${instances}; do
  select_instance ${instance}
  RO=$(mysql -sse 'select @@global.read_only')
  if [ ${RO} -eq 0 ]; then
    mysql -sse "set @@global.read_only=1"
    echo " [*] ${instance} read-write -> read-only"
  else
    echo " [.] ${instance} read-only already"
  fi
done

# Restore instance pointer
select_instance ${current_instance}
