#!/usr/local/bin/bash
MK_CONFDIR=/etc/check_mk
# Ports to check
Ports="$(fgrep port= $MK_CONFDIR/postgres.cfg | sed -e 's/port=//g' | tr '\n' ' ')"

# Don't change anything beyond this line

# Try to detect the postgres user
if id pgsql >/dev/null 2>&1; then
        USER=pgsql
elif id postgres >/dev/null 2>&1; then
        USER=postgres
else
        exit 0
fi

psql=$(which psql)

echo '<<<postgres_datadir>>>'
for Port in $Ports; do
        currinstance=$(grep -B2 -A1 $Port $MK_CONFDIR/postgres.cfg)
        dbname=$(echo "$currinstance" | grep dbname | sed -e 's/dbname=//g')
        instancename=$(echo "$currinstance" | egrep "\[.*\]" | sed -e 's/\[//g' -e 's/\]//g')
        echo "Port $Port - $dbname"

        OUTPUT="$(echo "show data_directory;" |\
        psql -X -p $Port -U postgres --variable ON_ERROR_STOP=1 -A -t -F' ' 2>/dev/null | grep -q "${instancename}";echo $?)"
        echo "$OUTPUT"
        sleep 0.5
done
