#!/usr/local/bin/bash
MK_CONFDIR=/etc/check_mk
# Ports to check
Ports="$(fgrep port= $MK_CONFDIR/postgres.cfg | sed -e 's/port=//g' | tr '\n' ' ')"

# Don't change anything beyond this line

# Try to detect the postgres user
if id pgsql >/dev/null 2>&1; then
        USER=pgsql
elif id postgres >/dev/null 2>&1; then
        USER=postgres
else
        exit 0
fi

psql=$(which psql)

echo '<<<postgres_blocking_extended>>>'
for Port in $Ports; do
        dbname=$(grep -B2 -A1 $Port $MK_CONFDIR/postgres.cfg | grep dbname | sed -e 's/dbname=//g')
        echo "Port $Port - $dbname"

        normal_out="$(echo "select case
                            when ((select count(*)
                            from dba.find_blocking_queries) > 0 )
                            then (select count(*)
                            from dba.find_blocking_queries)
                            else 0 end" |\
        psql -X -p $Port -U postgres --variable ON_ERROR_STOP=1 -d ${dbname} -A -t -F' ' 2>/dev/null)"
        blocking=$(echo "$normal_out" | awk '{print $1}')

        if [[ "$blocking" -eq "0" ]]; then
              echo "${normal_out}
blocking"
        else
              if [[ "$blocking" -gt 0 ]]; then
                    ext_blocking=$(echo "with my_extended_sessions
                                         as (select pid,datname,usename,xact_start,query_start,query,addr
                                         from dba.pids_clients_servers_trx UNION
                                         select pid,datname,usename,xact_start,query_start,query,addr
                                         from dba.pids_clients_servers_ses),
                                         my_joined_sessions
                                         as (select a.pid,a.datname,a.usename,a.xact_start,a.query_start,a.query,
                                         case when b.addr is null
                                         then 'direct'
                                         else b.addr end
                                         from pg_stat_activity a left outer join my_extended_sessions b
                                         on a.pid = b.pid
                                         where a.pid = (select blocking_pid from dba.find_blocking_queries join pg_stat_activity
                                         on blocking_pid=pid order by query_start asc limit 1))
                                         select 'pid=' || pid || '\\n'
                                         || 'database=' || datname || '\\n'
                                         || 'user=' || usename || '\\n'
                                         || 'trx_start=' || xact_start || '\\n'
                                         || 'query_start=' || query_start || '\\n'
                                         || 'query=' || query || '\\n'
                                         || 'ip=' || addr
                                         from my_joined_sessions;" |\
                    psql -X -p ${Port} -U postgres --variable ON_ERROR_STOP=1 -d ${dbname} -A -t -F' ' | awk '{printf "%s\\n", $0}')
              else
                    ext_blocking=""
              fi


              echo "${normal_out}
blocking ${ext_blocking}"
        fi
        sleep 0.5
done



