  db_name = "pg_core_us_200_prod"
  db_instance_name = "pg-core-us-200-prod"
  db_type = "postgres"
  db_version = "POSTGRES_15"
  db_tier = "db-custom-4-15360"
  disk_size = 1000
  log_connections = "on"
  pg_cron = "on"
#  db_user_name = "my_test_app"
#  db_user_password = "gds123test"
  replica_count = 0
  max_worker_processes = 16
  max_logical_replication_workers = 12
  max_wal_senders = 12
  max_replication_slots = 12
