#!/usr/local/bin/bash
#
#        _/_/_/    _/_/      _/_/_/
#     _/        _/    _/  _/
#      _/_/    _/    _/  _/
#         _/  _/    _/  _/
#  _/_/_/      _/_/      _/_/_/
#

# help
print_usage (){
        echo ""
        echo "$0 -w --> warning count"
        echo "$0 -c --> critical count"
	echo "$0 -u --> user"
	echo "$0 -p --> port"
        echo "$0 -h --> this help"
	echo "$0 -s --> Socket to check"
        echo ""
        exit 3
}
# commandline options given?
if [ $# -lt 10 ]; then
        echo "- Not all arguments found!"
        print_usage
        exit 3
fi
# fetch commandline options
while test -n "$1"; do
        case "$1" in
        -w)
                warning=$2
                shift
        ;;
        -c)
                critical=$2
                shift
        ;;
	-s)
		Socket=$2
		shift
	;;
	-u)
		User=$2
		shift
	;;
	-p)
		Port=$2
		shift
	;;
        -h)
                print_usage
                shift
        esac
        shift
done
# run psql query
result=$(mysql -u ${User} -P ${Port} --${Socket} -e "select CASE when ( (
SELECT count(*)
    FROM
      INFORMATION_SCHEMA.COLUMNS
      INNER JOIN INFORMATION_SCHEMA.TABLES USING (TABLE_SCHEMA, TABLE_NAME)
    WHERE
      TABLE_SCHEMA NOT IN ('mysql', 'INFORMATION_SCHEMA', 'performance_schema')
      AND EXTRA='auto_increment')  = 0 ) then 0
      else 
      (
SELECT ROUND(MAX(AUTO_INCREMENT_RATIO)*100) as MAX_AUTO_INCREMENT_PERCENT
      FROM (SELECT
      TABLE_SCHEMA,
      TABLE_NAME,
      COLUMN_NAME,
      DATA_TYPE,
      COLUMN_TYPE,
      IF(
        LOCATE('unsigned', COLUMN_TYPE) > 0,
        1,
        0
      ) AS IS_UNSIGNED,
      (
        CASE DATA_TYPE
          WHEN 'tinyint' THEN 255
          WHEN 'smallint' THEN 65535
          WHEN 'mediumint' THEN 16777215
          WHEN 'int' THEN 4294967295
          WHEN 'bigint' THEN 18446744073709551615
        END >> IF(LOCATE('unsigned', COLUMN_TYPE) > 0, 0, 1)
      ) AS MAX_VALUE,
      AUTO_INCREMENT,
      AUTO_INCREMENT / (
        CASE DATA_TYPE
          WHEN 'tinyint' THEN 255
          WHEN 'smallint' THEN 65535
          WHEN 'mediumint' THEN 16777215
          WHEN 'int' THEN 4294967295
          WHEN 'bigint' THEN 18446744073709551615
        END >> IF(LOCATE('unsigned', COLUMN_TYPE) > 0, 0, 1)
      ) AS AUTO_INCREMENT_RATIO
    FROM
      INFORMATION_SCHEMA.COLUMNS
      INNER JOIN INFORMATION_SCHEMA.TABLES USING (TABLE_SCHEMA, TABLE_NAME)
    WHERE
      TABLE_SCHEMA NOT IN ('mysql', 'INFORMATION_SCHEMA', 'performance_schema')
      AND EXTRA='auto_increment')T
      )
      END; " -s -N)
# prevent calc without query output
if [ ! "$result" ]; then
        echo "- Got no Output from mysql client"
        exit 2
fi
# status logic
if [ "`echo "$result > $critical" | bc -l`" = "1" ]; then
	echo "result=${result}; CRIT - auto_inc is ${result}"
	exit 2
elif [ "`echo "$result > $warning" | bc -l`" = "1" ]; then
        echo "result=${result}; WARN - auto_inc is ${result}"
        exit 1
elif [ "`echo "$result < $critical" | bc -l`" = "1" ] && [ "`echo "$result < $warning" | bc -l`" = "1" ]; then
	echo "result=${result}; OK - auto_inc is ${result}"
	exit 0
else
	echo "- Unexpected Output from check"
	exit 3
fi
