#!/usr/local/bin/bash
#
#        _/_/_/    _/_/      _/_/_/
#     _/        _/    _/  _/
#      _/_/    _/    _/  _/
#         _/  _/    _/  _/
#  _/_/_/      _/_/      _/_/_/
#

trim() {
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"   
    echo -n "$var"
}

# help
print_usage (){
        echo ""
        echo "$0 -w --> warning count"
        echo "$0 -c --> critical count"
	echo "$0 -u --> user"
	echo "$0 -p --> port"
        echo "$0 -h --> this help"
	echo "$0 -s --> Socket to check"
        echo ""
        exit 3
}
# commandline options given?
if [ $# -lt 10 ]; then
        echo "- Not all arguments found!"
        print_usage
        exit 3
fi
# fetch commandline options
while test -n "$1"; do
        case "$1" in
        -w)
                warning=$2
                shift
        ;;
        -c)
                critical=$2
                shift
        ;;
	-s)
		Socket=$2
		shift
	;;
	-u)
		User=$2
		shift
	;;
	-p)
		Port=$2
		shift
	;;
        -h)
                print_usage
                shift
        esac
        shift
done
# run psql query
result1=$(mysql -u ${User} -P ${Port} --${Socket} -e "show status like 'Queries'" -s -N)
result1=${result1//Queries/}
#echo "the result1 is:${result1}"
sleep 5
result2=$(mysql -u ${User} -P ${Port} --${Socket} -e "show status like 'Queries'" -s -N)  
result2=${result2//Queries/}
#echo "the result2 is:${result2}"

result=$(((result2-result1) / 10 ))
#echo "the result is:${result}"

# prevent calc without query output
if [ ! "$result" ]; then
        echo "- Got no Output from mysql client"
        exit 2
fi
# status logic
if [ "`echo "$result > $critical" | bc -l`" = "1" ]; then
	echo "result=${result}; CRIT - Queries per Second are ${result}"
	exit 2
elif [ "`echo "$result > $warning" | bc -l`" = "1" ]; then
        echo "result=${result}; WARN - Queries per Second ${result}"
        exit 1
elif [ "`echo "$result < $critical" | bc -l`" = "1" ] && [ "`echo "$result < $warning" | bc -l`" = "1" ]; then
	echo "result=${result}; OK - Queries per Second ${result}"
	exit 0
else
	echo "- Unexpected Output from check"
	exit 3
fi
