  db_name = "pg_noncore_gl_005_stg"
  db_instance_name = "pg-noncore-gl-005-stg-replica"
  db_type = "postgres"
  db_version = "POSTGRES_15"
  db_tier = "db-custom-2-7680"
  db_tier_replica = "db-custom-2-7680"
  disk_size = 500
  log_connections = "on"
  pg_cron = "on"
#  db_user_name = "my_test_app"
#  db_user_password = "gds123test"
  replica_count = 0
  master_instance_name = "pg-noncore-gl-005-stg"
  backup_location = "eu" 
