  db_name = "pg_core_emea_800_stg"
  db_instance_name = "pg-core-emea-800-stg"
  db_type = "postgres"
  db_version = "POSTGRES_15"
  db_tier = "db-custom-4-15360"
  disk_size = 1000
  max_connections = 2669
  autovacuum_analyze_scale_factor = 0.01
  autovacuum_max_workers = 10
  default_statistics_target = 1000
  log_connections = "on"
  log_temp_files = 0
  pg_cron = "on"
  work_mem = "22999"
#  db_user_name = "my_test_app"
#  db_user_password = "gds123test"
  replica_count = 1
  max_worker_processes = 16
  max_logical_replication_workers = 12
  max_wal_senders = 10
  max_replication_slots = 10
