  db_name = "pg_noncore_emea_561_stg"
  db_instance_name = "pg-noncore-emea-561-stg"
  db_type = "postgres"
  db_version = "POSTGRES_15"
  db_tier = "db-custom-8-30720"
  disk_size = 1000
  max_connections = 5669
  autovacuum_analyze_scale_factor = 0.01
  autovacuum_max_workers = 10
  default_statistics_target = 1000
  log_connections = "on"
  log_temp_files = 0
  pg_cron = "on"
  work_mem = "12999"
#  db_user_name = "my_test_app"
#  db_user_password = "gds123test"
  replica_count = 1
  max_worker_processes = 32
  max_logical_replication_workers = 24
  max_wal_senders = 25
  max_replication_slots = 20
