  db_name = "pg_core_gl_982_prod"
  db_instance_name = "pg-core-gl-982-prod-replica"
  db_type = "postgres"
  db_version = "POSTGRES_15"
  db_tier = "db-custom-8-30720"
  disk_size = 2000
  max_connections = 5669
  log_connections = "on"
  pg_cron = "on"
#  db_user_name = "my_test_app"
#  db_user_password = "gds123test"
  replica_count = 0
  max_worker_processes = 32
  max_logical_replication_workers = 24
  max_wal_senders = 25
  max_replication_slots = 20
  master_instance_name = "pg-core-gl-982-prod"
