#!/usr/local/bin/bash
MK_CONFDIR=/etc/check_mk
# instances to check
echo '<<<mysql_autoinc>>>'
for mysqlinstance in $(grep -e '\[.*\]' $MK_CONFDIR/mysql.cfg | sed -e 's/\[//g' -e 's/\]//g' | tr '\n' ' ');do
    currentinstance=$(grep -A3 "\[${mysqlinstance}\]" $MK_CONFDIR/mysql.cfg)
    port=$(echo "$currentinstance" | grep "port=" | sed -e 's/port=//')
    socket=$(echo "$currentinstance" | grep "socket=")
    name=$(echo "${port} - ${mysqlinstance}")

    result=$(mysql -u root -P ${port} --${socket} -e "select CASE when ( (
        SELECT count(*)
        FROM
          INFORMATION_SCHEMA.COLUMNS
          INNER JOIN INFORMATION_SCHEMA.TABLES USING (TABLE_SCHEMA, TABLE_NAME)
        WHERE
          TABLE_SCHEMA NOT IN ('mysql', 'INFORMATION_SCHEMA', 'performance_schema')
          AND EXTRA='auto_increment')  = 0 ) then 0
          else
          (
        SELECT ROUND(MAX(AUTO_INCREMENT_RATIO)*100) as MAX_AUTO_INCREMENT_PERCENT
          FROM (SELECT
          TABLE_SCHEMA,
          TABLE_NAME,
          COLUMN_NAME,
          DATA_TYPE,
          COLUMN_TYPE,
          IF(
            LOCATE('unsigned', COLUMN_TYPE) > 0,
            1,
            0
          ) AS IS_UNSIGNED,
          (
            CASE DATA_TYPE
              WHEN 'tinyint' THEN 255
              WHEN 'smallint' THEN 65535
              WHEN 'mediumint' THEN 16777215
              WHEN 'int' THEN 4294967295
              WHEN 'bigint' THEN 18446744073709551615
            END >> IF(LOCATE('unsigned', COLUMN_TYPE) > 0, 0, 1)
          ) AS MAX_VALUE,
          AUTO_INCREMENT,
          AUTO_INCREMENT / (
            CASE DATA_TYPE
              WHEN 'tinyint' THEN 255
              WHEN 'smallint' THEN 65535
              WHEN 'mediumint' THEN 16777215
              WHEN 'int' THEN 4294967295
              WHEN 'bigint' THEN 18446744073709551615
            END >> IF(LOCATE('unsigned', COLUMN_TYPE) > 0, 0, 1)
          ) AS AUTO_INCREMENT_RATIO
        FROM
          INFORMATION_SCHEMA.COLUMNS
          INNER JOIN INFORMATION_SCHEMA.TABLES USING (TABLE_SCHEMA, TABLE_NAME)
        WHERE
          TABLE_SCHEMA NOT IN ('mysql', 'INFORMATION_SCHEMA', 'performance_schema')
          AND EXTRA='auto_increment')T
          )
          END; " -s -N 2> /dev/null)

    exit_code=$(echo $?)

    if [[ "${exit_code}" -eq "1" ]]; then
        result="-1"
    fi

    echo "[[$name]]"
    echo "$result"
    sleep 0.5
done
