  db_name = "pg_admin_111"
  db_instance_name = "pg-admin-prod-111"
  db_type = "postgres"
  db_version = "POSTGRES_15"
  db_tier = "db-custom-1-3840"
  disk_size = 1000
  log_connections = "on"
  max_wal_senders = 25
  pg_cron = "on"
#  db_user_name = "my_test_app"
#  db_user_password = "gds123test"
  replica_count = 0
  max_worker_processes = 10
  max_logical_replication_workers = 6
  max_replication_slots = 20
