#!/usr/local/bin/bash
MK_CONFDIR=/etc/check_mk
# Ports to check
Ports="$(fgrep port= $MK_CONFDIR/postgres.cfg | sed -e 's/port=//g' | tr '\n' ' ')"

# Don't change anything beyond this line

# Try to detect the postgres user
if id pgsql >/dev/null 2>&1; then
	USER=pgsql
elif id postgres >/dev/null 2>&1; then
	USER=postgres
else
	exit 0
fi

psql=$(which psql)

echo '<<<postgres_sessions_multi>>>'
for Port in $Ports; do
  dbname=$(grep -B2 -A1 $Port $MK_CONFDIR/postgres.cfg | grep dbname | sed -e 's/dbname=//g')
	echo "Port $Port - $dbname"

	OUTPUT="$(echo "select state, count(*) from pg_stat_activity group by state;" |\
	su - $USER -c "psql -X -p $Port -U postgres --variable ON_ERROR_STOP=1 -d postgres -A -t -F' '" 2>/dev/null)"
	real_output=$(echo "$OUTPUT" | grep -E "^active [0-9]+|^idle [0-9]+" | sed -e "s/active/f/" -e "s/idle/t/g")

  if [ ! "$(echo "$real_output" | grep -E "^f")" ]; then
    echo "f 9999999999"
    echo "$real_output" | tr -d '\n'
  else
    echo "$real_output"
  fi
  if [ ! "$(echo "$real_output" | grep -E "^t")" ]; then
    echo "t 0"
  fi
  sleep 0.5
done

stamp=$(date +%s)
lifetime=$(realpath $0 | egrep -o "[0-9]+")

if [[ -z "${lifetime}" ]]; then
  lifetime=60
else
  lifetime=$((lifetime * 2))
fi

echo "<<<postgres_stat_database_multi:sep(59):cached(${stamp},${lifetime})>>>"
echo "measured_at ${stamp}"
echo 'datid;datname;numbackends;xact_commit;xact_rollback;blks_read;blks_hit;idxscan;idxtupread;idxtupfetch;idxblksread;idxblkshit;seqscan;seqtupread;tup_returned;tup_fetched;tup_inserted;tup_updated;tup_deleted;datsize'
for Port in $Ports; do
        dbname=$(grep -B2 -A1 $Port $MK_CONFDIR/postgres.cfg | grep dbname | sed -e 's/dbname=//g')
        echo "SELECT datid,
                datname,
                numbackends,
                xact_commit,
                xact_rollback,
                blks_read,
                blks_hit,
                (SELECT SUM(idx_scan) FROM pg_stat_user_indexes) AS idxscan,
                COALESCE((SELECT SUM(idx_tup_read) FROM pg_stat_user_indexes),0) AS idxtupread,
                COALESCE((SELECT SUM(idx_tup_fetch) FROM pg_stat_user_indexes),0) AS idxtupfetch,
                COALESCE((SELECT SUM(idx_blks_read) FROM pg_statio_user_indexes),0) AS idxblksread,
                COALESCE((SELECT SUM(idx_blks_hit) FROM pg_statio_user_indexes),0) AS idxblkshit,
                COALESCE((SELECT SUM(seq_scan) FROM pg_stat_user_tables),0) AS seqscan,
                COALESCE((SELECT SUM(seq_tup_read) FROM pg_stat_user_tables),0) AS seqtupread,
                tup_returned,
                tup_fetched,
                tup_inserted,
                tup_updated,
                tup_deleted,
                pg_database_size(datname) AS datsize
                FROM pg_stat_database
                WHERE datname = '$dbname';" |\
        su - $USER -c "psql -X -p $Port -U postgres -d $dbname -A -F';' 2>/dev/null" | sed '$d' | sed '1,1d' | sed -e "s/;/;$Port - /"
        sleep 0.5
done
