#!/usr/local/bin/bash
MK_CONFDIR=/etc/check_mk
# instances to check
echo '<<<mysql_read_only_master>>>'
for mysqlinstance in $(grep -e '\[.*\]' $MK_CONFDIR/mysql.cfg | sed -e 's/\[//g' -e 's/\]//g' | tr '\n' ' ');do
    currentinstance=$(grep -A3 "\[${mysqlinstance}\]" $MK_CONFDIR/mysql.cfg)
    port=$(echo "$currentinstance" | grep "port=" | sed -e 's/port=//')
    socket=$(echo "$currentinstance" | grep "socket=")
    name=$(echo "${port} - ${mysqlinstance}")

    result=$(mysql -u root -P ${port} --${socket} -e "SELECT case
                                                      WHEN (@@read_only=0)
                                                      THEN 0
                                                      ELSE 2 end;" -s -N 2> /dev/null)
    exit_code=$(echo $?)

    if [[ "${exit_code}" -eq "1" ]]; then
        result="-1"
    fi

    echo "[[$name]]"
    echo "$result"
    sleep 0.5
done
