

hostlist="finch-redis1.snc1,finch-redis2.snc1,finch-redis3.snc1,finch-redis4.snc1,general-redis1.snc1,general-redis2.snc1,quantum-lead-redis2.snc1,transporter-redis1.snc1,transporter-redis2.snc1,badges-redis2.dub1,goods-redis1.dub1,rocketman-redis1.dub1,rocketman-redis2.dub1,seo-services-redis1.dub1,seo-services-redis2.dub1,seo-services-redis3.dub1,accounting-memcache1.sac1,accounting-memcache1.snc1,accounting-memcache2.sac1,accounting-memcache2.snc1,accounting-memcache3.sac1,accounting-memcache3.snc1,booking-engine-3rd-party-memcached1.dub1,booking-engine-3rd-party-memcached1.sac1,booking-engine-3rd-party-memcached1.snc1,booking-engine-3rd-party-memcached2.dub1,booking-engine-3rd-party-memcached2.sac1,booking-engine-3rd-party-memcached2.snc1,booking-engine-api-memcached1.sac1,booking-engine-api-memcached1.snc1,booking-engine-api-memcached2.sac1,booking-engine-api-memcached2.snc1,booking-engine-appointments-memcached1.dub1,booking-engine-appointments-memcached1.sac1,booking-engine-appointments-memcached1.snc1,booking-engine-appointments-memcached2.dub1,booking-engine-appointments-memcached2.sac1,booking-engine-appointments-memcached2.snc1,geo-taxonomy-memcached1.dub1,geo-taxonomy-memcached1.sac1,geo-taxonomy-memcached1.snc1,geo-taxonomy-memcached2.dub1,geo-taxonomy-memcached2.sac1,geo-taxonomy-memcached2.snc1,geo-taxonomy-memcached3.dub1,geo-taxonomy-memcached3.snc1,geo-taxonomy-memcached4.dub1,geo-taxonomy-memcached4.snc1,goods-memcache1.dub1,goods-memcache1.snc1,goods-memcache2.dub1,goods-memcache2.snc1,goods-memcache3.snc1,goods-memcache.snc1,itier-getaways-extranet-memcache-app1.sac1,itier-getaways-extranet-memcache-app1.snc1,itier-getaways-extranet-memcache-app2.sac1,itier-getaways-extranet-memcache-app2.snc1,orders-memcache1.dub1,orders-memcache1.sac1,orders-memcache1.snc1,orders-memcache2.dub1,orders-memcache2.sac1,orders-memcache3.snc1,users-service-memcache1.dub1,users-service-memcache1.sac1,users-service-memcache1.snc1,users-service-memcache2.dub1,users-service-memcache2.sac1,users-service-memcache2.snc1,users-service-memcache3.snc1,web-general-memcache1.snc1,web-general-memcache2.snc1,web-general-memcache3.snc1,web-general-memcache4.snc1,web-session-memcache1.snc1"


pdsh -f1 -w  $hostlist uptime
pdsh -f1 -w  $hostlist "cat /etc/logrotate.d/syslog"


